"use client";

import React, { useEffect, useState } from "react";
import Link from "next/link";
import { motion } from "framer-motion";
import { 
  Calendar, 
  FileCheck, 
  Mail, 
  Clock, 
  PlusCircle,
  Upload,
  Award,
  Send,
  BarChart,
  CheckCircle2,
  AlertCircle
} from "lucide-react";
import clsx from "clsx";
import { collection, getCountFromServer, query, where, getDocs } from "firebase/firestore";
import { db } from "@/lib/firebase/client";
import { useAuth } from "@/context/AuthContext";

export default function CoordinatorDashboard() {
  const { userProfile, currentUser } = useAuth();
  const coordinatorName = userProfile?.name || currentUser?.displayName || "Coordinator";

  const [stats, setStats] = useState({
    events: 0,
    certificates: 0,
    emailsSent: 0,
    pending: 0,
    failed: 0,
    yetToSend: 0
  });
  const [mounted, setMounted] = useState(false);
  
  useEffect(() => {
    setMounted(true);
    
    const fetchData = async () => {
      try {
        if (!db || !currentUser) return;
        
        const certsQuery = query(collection(db, "certificates"), where("coordinatorId", "==", currentUser.uid));
        const eventsQuery = query(collection(db, "events"), where("coordinatorId", "==", currentUser.uid));
        
        const eventsSnap = await getCountFromServer(eventsQuery);
        
        // Let's get all certs to calculate email analytics
        const certsData = await getDocs(certsQuery);
        const certs = certsData.docs.map(doc => doc.data());
        
        const totalCerts = certs.length;
        const sent = certs.filter(c => c.status === "sent").length;
        const pending = certs.filter(c => c.status === "pending").length;
        const failed = certs.filter(c => c.status === "failed").length;
        const yetToSend = totalCerts - sent;
        
        setStats({
          events: eventsSnap.data().count,
          certificates: totalCerts,
          emailsSent: sent, 
          pending: pending,
          failed: failed,
          yetToSend: yetToSend
        });

      } catch (error) {
        console.error("Failed to fetch data from Firestore", error);
      }
    };
    
    fetchData();
  }, [currentUser]);

  if (!mounted) return null;

  const STAT_CARDS = [
    { label: "My Events", value: stats.events.toString(), icon: Calendar, color: "indigo", sub: "Total managed" },
    { label: "Certificates", value: stats.certificates.toString(), icon: FileCheck, color: "amber", sub: "Generated by you" },
    { label: "Emails Sent", value: stats.emailsSent.toString(), icon: Mail, color: "emerald", sub: "Successfully delivered" },
    { label: "Pending", value: stats.pending.toString(), icon: Clock, color: "blue", sub: "Queued for send" },
  ];

  // Calculate percentages for the analytics bar
  const totalEmails = Math.max(stats.certificates, 1); // prevent division by zero
  const sentPercent = Math.round((stats.emailsSent / totalEmails) * 100) || 0;
  const pendingPercent = Math.round((stats.pending / totalEmails) * 100) || 0;
  const failedPercent = Math.round((stats.failed / totalEmails) * 100) || 0;

  return (
    <div className="space-y-8 max-w-7xl mx-auto pb-10">
      
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-end justify-between gap-4">
        <div>
          <p className="text-xs font-bold uppercase tracking-widest text-muted-foreground mb-1">Your Workspace</p>
          <h1 className="text-3xl font-bold text-foreground tracking-tight">
            Welcome back, <span className="text-accent">{coordinatorName}</span>
          </h1>
        </div>
        <div className="flex items-center gap-3">
          <Link
            href="/coordinator/events"
            className="inline-flex items-center gap-2 px-4 py-2 bg-card border border-border rounded-xl text-sm font-semibold text-foreground hover:bg-accent/10 hover:text-accent hover:border-accent/30 transition-all shadow-sm"
          >
            <PlusCircle size={16} />
            New Event
          </Link>
          <Link
            href="/coordinator/email-queue"
            className="inline-flex items-center gap-2 px-4 py-2 bg-primary rounded-xl text-sm font-semibold text-primary-foreground hover:opacity-90 transition-opacity shadow-sm"
          >
            <Send size={16} />
            Resume Sending
          </Link>
        </div>
      </div>

      {/* Stats Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        {STAT_CARDS.map((stat, idx) => {
          const Icon = stat.icon;
          return (
            <motion.div
              key={stat.label}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.4, delay: idx * 0.1 }}
              whileHover={{ y: -4 }}
              className="bg-card p-6 rounded-2xl border border-border shadow-sm hover:shadow-md transition-all flex flex-col justify-between min-h-[140px] relative overflow-hidden group"
            >
              <div className="absolute -bottom-6 -right-6 opacity-5 group-hover:opacity-10 transition-transform duration-500 group-hover:scale-110 pointer-events-none">
                 <Icon size={100} className="text-foreground" />
              </div>
              <div className="flex items-start justify-between mb-4 relative z-10">
                <p className="text-sm font-semibold text-muted-foreground">{stat.label}</p>
                <div className={clsx(
                  "p-2 rounded-xl border border-transparent shadow-sm",
                  stat.color === 'indigo' && "bg-indigo-500/10 text-indigo-500 border-indigo-500/20",
                  stat.color === 'emerald' && "bg-emerald-500/10 text-emerald-500 border-emerald-500/20",
                  stat.color === 'amber' && "bg-amber-500/10 text-amber-500 border-amber-500/20",
                  stat.color === 'blue' && "bg-blue-500/10 text-blue-500 border-blue-500/20",
                )}>
                  <Icon size={18} />
                </div>
              </div>
              <div className="relative z-10">
                <h3 className="text-3xl font-bold text-foreground mb-1 tracking-tight">{stat.value}</h3>
                <p className="text-xs font-medium text-muted-foreground/80">{stat.sub}</p>
              </div>
            </motion.div>
          );
        })}
      </div>

      {/* Bottom Row: Analytics + Quick Actions */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">

        {/* Real-time Email Analytics */}
        <div className="lg:col-span-2 bg-card border border-border rounded-2xl p-6 lg:p-8 shadow-sm flex flex-col min-h-[320px]">
          <div className="flex items-center justify-between mb-8">
            <div>
              <h3 className="text-lg font-bold text-foreground flex items-center gap-2">
                <BarChart className="w-5 h-5 text-accent" />
                Delivery Analytics
              </h3>
              <p className="text-sm text-muted-foreground mt-1">Real-time status of your email pipeline</p>
            </div>
            <Link href="/coordinator/email-queue" className="text-sm font-semibold text-accent hover:underline">
              View Queue
            </Link>
          </div>
          
          <div className="flex-1 flex flex-col justify-center">
            {/* Visual Progress Bar */}
            <div className="w-full h-4 rounded-full bg-muted overflow-hidden flex mb-8">
              <div style={{ width: `${sentPercent}%` }} className="h-full bg-emerald-500 transition-all duration-1000" />
              <div style={{ width: `${pendingPercent}%` }} className="h-full bg-blue-500 transition-all duration-1000" />
              <div style={{ width: `${failedPercent}%` }} className="h-full bg-red-500 transition-all duration-1000" />
            </div>

            {/* Metrics Breakdown */}
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
              <div className="p-4 rounded-xl border border-border bg-background/50 flex items-center gap-4">
                 <div className="w-10 h-10 rounded-full bg-emerald-500/10 flex items-center justify-center text-emerald-500 shrink-0">
                   <CheckCircle2 size={20} />
                 </div>
                 <div>
                   <p className="text-sm font-semibold text-muted-foreground">Sent</p>
                   <p className="text-2xl font-bold text-foreground">{stats.emailsSent}</p>
                 </div>
              </div>
              <div className="p-4 rounded-xl border border-border bg-background/50 flex items-center gap-4">
                 <div className="w-10 h-10 rounded-full bg-blue-500/10 flex items-center justify-center text-blue-500 shrink-0">
                   <Clock size={20} />
                 </div>
                 <div>
                   <p className="text-sm font-semibold text-muted-foreground">Pending</p>
                   <p className="text-2xl font-bold text-foreground">{stats.pending}</p>
                 </div>
              </div>
              <div className="p-4 rounded-xl border border-border bg-background/50 flex items-center gap-4">
                 <div className="w-10 h-10 rounded-full bg-amber-500/10 flex items-center justify-center text-amber-500 shrink-0">
                   <AlertCircle size={20} />
                 </div>
                 <div>
                   <p className="text-sm font-semibold text-muted-foreground">Yet to Send</p>
                   <p className="text-2xl font-bold text-foreground">{stats.yetToSend}</p>
                 </div>
              </div>
            </div>
          </div>
        </div>

        {/* Quick Actions */}
        <div className="bg-card border border-border rounded-2xl p-6 shadow-sm flex flex-col min-h-[320px]">
          <h3 className="text-lg font-bold text-foreground mb-4">Quick actions</h3>
          <div className="flex-1 flex flex-col gap-2">
            <Link
              href="/coordinator/events"
              className="flex items-center gap-4 p-3 rounded-xl hover:bg-accent/5 border border-transparent hover:border-accent/20 transition-all group"
            >
              <div className="w-10 h-10 rounded-xl bg-indigo-500/10 text-indigo-500 flex items-center justify-center flex-shrink-0 group-hover:scale-110 transition-transform">
                <PlusCircle size={20} />
              </div>
              <div>
                <p className="text-sm font-bold text-foreground group-hover:text-accent transition-colors">Manage Events</p>
                <p className="text-xs font-medium text-muted-foreground">Create or view your events</p>
              </div>
            </Link>

            <Link
              href="/coordinator/participants"
              className="flex items-center gap-4 p-3 rounded-xl hover:bg-accent/5 border border-transparent hover:border-accent/20 transition-all group"
            >
              <div className="w-10 h-10 rounded-xl bg-purple-500/10 text-purple-500 flex items-center justify-center flex-shrink-0 group-hover:scale-110 transition-transform">
                <Upload size={20} />
              </div>
              <div>
                <p className="text-sm font-bold text-foreground group-hover:text-accent transition-colors">Manage participants</p>
                <p className="text-xs font-medium text-muted-foreground">Upload or edit participants</p>
              </div>
            </Link>

            <Link
              href="/coordinator/certificates"
              className="flex items-center gap-4 p-3 rounded-xl hover:bg-accent/5 border border-transparent hover:border-accent/20 transition-all group"
            >
              <div className="w-10 h-10 rounded-xl bg-amber-500/10 text-amber-500 flex items-center justify-center flex-shrink-0 group-hover:scale-110 transition-transform">
                <Award size={20} />
              </div>
              <div>
                <p className="text-sm font-bold text-foreground group-hover:text-accent transition-colors">View certificates</p>
                <p className="text-xs font-medium text-muted-foreground">Generated PDF history</p>
              </div>
            </Link>

            <Link
              href="/coordinator/email-queue"
              className="flex items-center gap-4 p-3 rounded-xl hover:bg-accent/5 border border-transparent hover:border-accent/20 transition-all group"
            >
              <div className="w-10 h-10 rounded-xl bg-emerald-500/10 text-emerald-500 flex items-center justify-center flex-shrink-0 group-hover:scale-110 transition-transform">
                <Send size={20} />
              </div>
              <div>
                <p className="text-sm font-bold text-foreground group-hover:text-accent transition-colors">Send queue</p>
                <p className="text-xs font-medium text-muted-foreground">Manage email delivery</p>
              </div>
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
}
