"use client";

import React, { useEffect, useState } from "react";
import { collection, query, where, getDocs } from "firebase/firestore";
import { db } from "@/lib/firebase/client";
import { useStore } from "@/lib/store";

export default function CoordinatorCertificatesPage() {
  const { user } = useStore();
  const [certificates, setCertificates] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchCerts = async () => {
      if (!db || !user?.email) return;

      try {
        const cRef = collection(db, "certificates");
        const q = query(cRef, where("coordinatorEmail", "==", user.email));
        const cSnap = await getDocs(q);
        
        let cList: any[] = [];
        cSnap.forEach((doc) => {
          cList.push({ id: doc.id, ...doc.data() });
        });

        setCertificates(cList);
      } catch (error) {
        console.error("Error fetching certificates:", error);
      } finally {
        setLoading(false);
      }
    };

    fetchCerts();
  }, [user]);

  return (
    <>
      <div className="breadcrumb">Home &nbsp;›&nbsp; <b>Certificates</b></div>
      <div className="page-head" style={{ marginBottom: "2rem" }}>
        <div>
          <h1>Generated Certificates</h1>
          <p style={{ color: "var(--text-dim)", marginTop: "0.5rem" }}>
            View all certificates generated by your events.
          </p>
        </div>
      </div>

      <div className="panel">
        <div className="panel-head">
          <h3>All Certificates ({certificates.length})</h3>
        </div>
        <table>
          <thead>
            <tr>
              <th>Drive Link</th>
              <th>Generated At</th>
            </tr>
          </thead>
          <tbody>
            {loading ? (
              <tr><td colSpan={2} style={{ textAlign: 'center', padding: '20px', color: '#635c7f' }}>Loading...</td></tr>
            ) : certificates.length === 0 ? (
              <tr><td colSpan={2} style={{ textAlign: 'center', padding: '20px', color: '#635c7f' }}>No certificates generated yet.</td></tr>
            ) : (
              certificates.map(c => (
                <tr key={c.id}>
                  <td>
                    <a href={`https://drive.google.com/file/d/${c.driveFileId}/view`} target="_blank" rel="noopener noreferrer" style={{ color: "var(--accent)" }}>
                      View in Drive
                    </a>
                  </td>
                  <td>{new Date(c.createdAt).toLocaleString()}</td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>
    </>
  );
}
